server:
  port: ${port:8080}
spring:
  #thymeleaf:
  #≈‰÷√ƒ£∞Â
    #prefix: classpath:/templates/
    #suffix: .html
  mvc:
     view:
         prefix: /WEB-INF/view/
         suffix: .jsp
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aaa?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
